"""DOCX report generator using python-docx with Avennorth branding."""

from __future__ import annotations

import logging
from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor

from bearing.api.schemas import AssessmentResponse, DimensionScoreResponse, FindingResponse

logger = logging.getLogger(__name__)

# Avennorth brand colors
OBSIDIAN_RGB = RGBColor(0x1C, 0x19, 0x17)
LIME_RGB = RGBColor(0x39, 0xFF, 0x14)
GRAY_RGB = RGBColor(0xA8, 0xA2, 0x9E)


class DOCXReportGenerator:
    """Generates branded DOCX reports for assessments."""

    def generate_health_scorecard(
        self,
        assessment: AssessmentResponse,
        scores: list[DimensionScoreResponse],
        findings: list[FindingResponse],
    ) -> bytes:
        """Generate a CMDB Health Scorecard DOCX."""
        doc = Document()

        # Title
        title = doc.add_heading("CMDB Health Scorecard", level=0)
        title.runs[0].font.color.rgb = OBSIDIAN_RGB

        # Assessment name and metadata
        doc.add_paragraph(assessment.name).runs[0].font.color.rgb = GRAY_RGB

        # Overall score
        score_para = doc.add_paragraph()
        run = score_para.add_run(f"{assessment.overall_score}/100")
        run.font.size = Pt(36)
        run.bold = True
        run.font.color.rgb = self._score_rgb(assessment.overall_score)

        run2 = score_para.add_run(f"  Grade: {assessment.grade}")
        run2.font.size = Pt(16)

        # Key metrics
        doc.add_paragraph(f"Maturity Level: {assessment.maturity_level} — {assessment.maturity_label}")
        doc.add_paragraph(f"Estimated Technical Debt: ${assessment.technical_debt_estimate:,.0f}")
        doc.add_paragraph(f"Total Findings: {assessment.findings_count} ({assessment.critical_findings} critical)")
        doc.add_paragraph(f"CIs Assessed: {assessment.ci_count_assessed:,}")

        # Dimension scores table
        doc.add_heading("Dimension Scores", level=1)
        table = doc.add_table(rows=1, cols=4)
        table.style = "Light Shading Accent 1"

        headers = table.rows[0].cells
        headers[0].text = "Dimension"
        headers[1].text = "Score"
        headers[2].text = "Weight"
        headers[3].text = "Status"

        for score in scores:
            row = table.add_row().cells
            row[0].text = score.dimension.value.replace("_", " ").title()
            row[1].text = str(score.score)
            row[2].text = f"{score.weight:.0%}"
            row[3].text = "Good" if score.score >= 75 else "Needs Work" if score.score >= 40 else "Critical"

        # Top findings
        doc.add_heading("Top Findings", level=1)
        critical_findings = sorted(
            findings,
            key=lambda f: {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}.get(f.severity.value, 5),
        )[:10]

        for finding in critical_findings:
            para = doc.add_paragraph()
            severity_run = para.add_run(f"[{finding.severity.value.upper()}] ")
            severity_run.bold = True
            para.add_run(finding.title)

        # AI Summary (if available)
        if assessment.ai_summary:
            doc.add_heading("AI Analysis", level=1)
            doc.add_paragraph(assessment.ai_summary)

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph("Generated by Avennorth Bearing")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.color.rgb = GRAY_RGB
        footer.runs[0].font.size = Pt(8)

        output = BytesIO()
        doc.save(output)
        return output.getvalue()

    @staticmethod
    def _score_rgb(score: int) -> RGBColor:
        if score >= 75:
            return RGBColor(0x22, 0xC5, 0x5E)
        if score >= 40:
            return RGBColor(0xF5, 0x9E, 0x0B)
        return RGBColor(0xEF, 0x44, 0x44)
