import type { SupabaseClient } from '@supabase/supabase-js';

/**
 * Configuration for continuous monitoring of a ServiceNow instance.
 */
export interface MonitoringConfig {
  connectionId: string;
  orgId: string;
  /** How often to run recurring scans (in hours). */
  intervalHours: number;
  alertThresholds: {
    /** Alert if the health score drops by this many points between assessments. */
    healthScoreDrop: number;
    /** Alert if this many new critical findings appear. */
    newCriticalFindings: number;
  };
}

/**
 * An alert generated by comparing two assessments.
 */
export interface Alert {
  type: 'health_score_drop' | 'new_critical_findings' | 'score_improvement';
  severity: 'critical' | 'warning' | 'info';
  message: string;
  currentValue: number;
  previousValue?: number;
  delta?: number;
}

/**
 * A single point in an assessment trend line.
 */
export interface TrendPoint {
  assessmentId: string;
  date: string;
  healthScore: number;
  findingCount: number;
  criticalCount: number;
}

/** Default alert thresholds when not specified by monitoring config. */
const DEFAULT_THRESHOLDS = {
  healthScoreDrop: 10,
  newCriticalFindings: 1,
};

/**
 * Continuous monitoring engine. Compares sequential assessments to detect
 * regressions, improvements, and new critical findings. Provides trend
 * data for multi-assessment analysis.
 */
export class ContinuousMonitor {
  constructor(private supabase: SupabaseClient) {}

  /**
   * Compare two assessments and generate alerts for significant changes.
   *
   * If previousAssessmentId is not provided, the method fetches the most
   * recent prior assessment for the same connection.
   */
  async checkForAlerts(
    assessmentId: string,
    previousAssessmentId?: string,
  ): Promise<Alert[]> {
    // Fetch the current assessment
    const { data: current, error: currentError } = await this.supabase
      .from('assessments')
      .select('id, health_score, instance_connection_id, created_at')
      .eq('id', assessmentId)
      .single();

    if (currentError || !current) {
      throw new Error(
        `Failed to fetch assessment ${assessmentId}: ${currentError?.message ?? 'not found'}`,
      );
    }

    // Resolve previous assessment
    let previous: typeof current | null = null;

    if (previousAssessmentId) {
      const { data, error } = await this.supabase
        .from('assessments')
        .select('id, health_score, instance_connection_id, created_at')
        .eq('id', previousAssessmentId)
        .single();

      if (!error && data) {
        previous = data;
      }
    } else {
      // Find the most recent completed assessment for the same connection
      const { data, error } = await this.supabase
        .from('assessments')
        .select('id, health_score, instance_connection_id, created_at')
        .eq('instance_connection_id', current.instance_connection_id)
        .eq('status', 'complete')
        .neq('id', assessmentId)
        .order('created_at', { ascending: false })
        .limit(1)
        .single();

      if (!error && data) {
        previous = data;
      }
    }

    // If there is no previous assessment, no comparison can be made
    if (!previous) {
      return [];
    }

    // Fetch monitoring config thresholds (if stored), or use defaults
    const thresholds = await this.getThresholds(
      current.instance_connection_id as string,
    );

    const alerts: Alert[] = [];

    const currentScore = (current.health_score as number) ?? 0;
    const previousScore = (previous.health_score as number) ?? 0;
    const scoreDelta = currentScore - previousScore;

    // Check for health score drop
    if (scoreDelta < 0 && Math.abs(scoreDelta) >= thresholds.healthScoreDrop) {
      alerts.push({
        type: 'health_score_drop',
        severity: Math.abs(scoreDelta) >= thresholds.healthScoreDrop * 2
          ? 'critical'
          : 'warning',
        message: `Health score dropped by ${Math.abs(scoreDelta)} points (from ${previousScore} to ${currentScore}).`,
        currentValue: currentScore,
        previousValue: previousScore,
        delta: scoreDelta,
      });
    }

    // Check for score improvement
    if (scoreDelta > 0) {
      alerts.push({
        type: 'score_improvement',
        severity: 'info',
        message: `Health score improved by ${scoreDelta} points (from ${previousScore} to ${currentScore}).`,
        currentValue: currentScore,
        previousValue: previousScore,
        delta: scoreDelta,
      });
    }

    // Count critical findings in both assessments
    const [currentCriticals, previousCriticals] = await Promise.all([
      this.countCriticalFindings(assessmentId),
      this.countCriticalFindings(previous.id as string),
    ]);

    const newCriticals = currentCriticals - previousCriticals;

    if (newCriticals >= thresholds.newCriticalFindings) {
      alerts.push({
        type: 'new_critical_findings',
        severity: 'critical',
        message: `${newCriticals} new critical finding(s) detected (was ${previousCriticals}, now ${currentCriticals}).`,
        currentValue: currentCriticals,
        previousValue: previousCriticals,
        delta: newCriticals,
      });
    }

    return alerts;
  }

  /**
   * Retrieve trend data for the last N assessments of a connection.
   */
  async getAssessmentTrend(
    connectionId: string,
    limit: number = 10,
  ): Promise<TrendPoint[]> {
    const { data: assessments, error } = await this.supabase
      .from('assessments')
      .select('id, created_at, health_score')
      .eq('instance_connection_id', connectionId)
      .eq('status', 'complete')
      .order('created_at', { ascending: true })
      .limit(limit);

    if (error) {
      throw new Error(`Failed to fetch assessment trend: ${error.message}`);
    }

    if (!assessments || assessments.length === 0) {
      return [];
    }

    // For each assessment, get finding counts
    const trendPoints: TrendPoint[] = [];

    for (const assessment of assessments) {
      const assessmentId = assessment.id as string;

      const [totalCount, criticalCount] = await Promise.all([
        this.countFindings(assessmentId),
        this.countCriticalFindings(assessmentId),
      ]);

      trendPoints.push({
        assessmentId,
        date: assessment.created_at as string,
        healthScore: (assessment.health_score as number) ?? 0,
        findingCount: totalCount,
        criticalCount,
      });
    }

    return trendPoints;
  }

  /** Count total findings for an assessment. */
  private async countFindings(assessmentId: string): Promise<number> {
    const { count, error } = await this.supabase
      .from('findings')
      .select('*', { count: 'exact', head: true })
      .eq('assessment_id', assessmentId);

    if (error) return 0;
    return count ?? 0;
  }

  /** Count critical findings for an assessment. */
  private async countCriticalFindings(assessmentId: string): Promise<number> {
    const { count, error } = await this.supabase
      .from('findings')
      .select('*', { count: 'exact', head: true })
      .eq('assessment_id', assessmentId)
      .eq('severity', 'critical');

    if (error) return 0;
    return count ?? 0;
  }

  /**
   * Retrieve alert thresholds for a connection, falling back to defaults.
   * In the future this could read from a monitoring_configs table.
   */
  private async getThresholds(
    _connectionId: string,
  ): Promise<{ healthScoreDrop: number; newCriticalFindings: number }> {
    // TODO: Read per-connection monitoring config from database when
    // the monitoring_configs table is created.
    return DEFAULT_THRESHOLDS;
  }
}
